import {
  AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN,
  AUTOMATION_CMD_FILE_NAME,
  BUILTIN_AUTOMATION_BRIDGE_SOURCE,
} from "../automation-bridge.js";
import type { BuiltinSkillDefinition } from "./types.js";

const DESCRIPTION =
  "Create visual architecture diagrams and structured report canvases inside Coder Studio when the user asks for a diagram, architecture overview, or when a visual would better explain a concept.";

const CONTENT = [
  "---",
  "name: coder-studio-canvas",
  `description: ${DESCRIPTION}`,
  "---",
  "",
  "# Coder Studio Canvas",
  "",
  "Use this skill when the user asks you to draw an architecture diagram, create a visual overview, or when a diagram or structured report would communicate something more clearly than plain text alone.",
  "",
  "Typical triggers:",
  "",
  '- "画一个架构图"',
  '- "draw an architecture diagram"',
  '- "show me how the system is structured"',
  '- "用图说明一下这个流程"',
  "- any request where boxes-and-arrows or a structured visual summary would help",
  "",
  "## Canvas Kinds",
  "",
  "There are two canvas kinds:",
  "",
  "- `architecture_canvas`: boxes, edges, annotations — best for system diagrams, data flow, module relationships",
  "- `report_canvas`: stats, markdown blocks, lists, tables, callouts — best for structured summaries, audits, status reports",
  "",
  "Choose the kind that fits the content. Default to `architecture_canvas` for diagrams.",
  "",
  "## Create And Open An Architecture Canvas",
  "",
  "Always use `--open` so the canvas appears as an editor tab immediately after creation.",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.create --kind architecture_canvas --title "<title>" --document-json '<json>' --open --json`,
  "```",
  "",
  "Document shape for `architecture_canvas` — uses Mermaid flowchart syntax in the `source` field:",
  "",
  "```json",
  "{",
  '  "summary": "One-line description of what this diagram shows.",',
  '  "diagram": {',
  '    "dsl": "mermaid",',
  '    "source": "flowchart LR\\nWebUI[Web UI] --> Server[API Server]\\nServer --> DB[Database]"',
  "  },",
  '  "annotations": [',
  '    { "title": "Boundary", "body": "Server owns all business logic." }',
  "  ]",
  "}",
  "```",
  "",
  "Mermaid flowchart rules:",
  "",
  "- First line: `flowchart LR` (left-to-right) or `flowchart TB` (top-to-bottom)",
  "- Node with label: `NodeID[Display Label]`",
  "- Directed edge: `A --> B` or with label: `A -->|label| B`",
  "- Subgraph: `subgraph GroupName` ... `end`",
  "- One statement per line, separated by `\\n` in the JSON string",
  "",
  "Keep diagrams focused. 3-10 nodes is usually right. Use annotations to explain boundaries, ownership, or important constraints.",
  "",
  "## Create And Open A Report Canvas",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.create --kind report_canvas --title "<title>" --document-json '<json>' --open --json`,
  "```",
  "",
  "Document shape for `report_canvas`:",
  "",
  "```json",
  "{",
  '  "summary": "Workspace audit summary.",',
  '  "stats": [',
  '    { "label": "Packages", "value": 6, "tone": "info" }',
  "  ],",
  '  "sections": [',
  "    {",
  '      "title": "Findings",',
  '      "blocks": [',
  '        { "type": "markdown", "markdown": "Key finding goes here." },',
  '        { "type": "callout", "tone": "warning", "title": "Risk", "body": "Explain the risk." },',
  "        {",
  '          "type": "chart",',
  '          "kind": "line",',
  '          "title": "Token Consumption",',
  '          "summary": "Prompt vs completion over the last 3 hours.",',
  '          "unit": "tokens",',
  '          "categories": ["09:00", "10:00", "11:00"],',
  '          "series": [',
  '            { "name": "Prompt", "values": [1200, 1800, 900] },',
  '            { "name": "Completion", "values": [400, 700, 500] }',
  "          ],",
  '          "showLegend": true',
  "        }",
  "      ]",
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "Block types: `markdown`, `stats`, `list`, `table`, `callout`, `chart`. Each section needs at least one block.",
  "Use `chart` blocks for already-known numeric data that benefits from a trend, comparison, or compact summary visual.",
  "Chart kinds: `line` for trends, `bar` for comparisons, and `sparkline` for dense inline summaries.",
  "Keep `categories` aligned with each series' `values` array and do not pass raw chart library options.",
  "",
  "## Canvas Source Files",
  "",
  "Every created canvas writes a readable `.coder-studio/canvases/<title-slug>.csc` file in the workspace. Treat that file path as the primary steady-state handle for opening and rendering canvases.",
  "",
  "Full source envelope example:",
  "",
  "```json",
  "{",
  '  "version": 1,',
  '  "kind": "architecture_canvas",',
  '  "title": "System Overview",',
  '  "document": {',
  '    "summary": "How the web UI, server, and database connect.",',
  '    "diagram": {',
  '      "dsl": "mermaid",',
  '      "source": "flowchart LR\\nWebUI[Web UI] --> Server[API Server]\\nServer --> DB[Database]"',
  "    },",
  '    "annotations": [',
  '      { "title": "Boundary", "body": "Server owns all business logic." }',
  "    ]",
  "  }",
  "}",
  "```",
  "",
  "## Open An Existing Canvas",
  "",
  "Prefer opening the `.csc` file path directly:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" ui.open-file --path .coder-studio/canvases/<title-slug>.csc --json`,
  "```",
  "",
  "If you only know the canvas id, `ui.open-canvas` remains available as a compatibility path:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" ui.open-canvas --canvas <canvas-id> --json`,
  "```",
  "",
  "Or list canvases first to find the id and source path you need:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.list --json`,
  "```",
  "",
  "## Update A Canvas",
  "",
  "Update when the content changes but the canvas identity should stay the same:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.update --canvas <canvas-id> --document-json '<json>' --json`,
  "```",
  "",
  "## Presets",
  "",
  "List built-in report canvas starters, then create from one when a standard chart/report scaffold is enough:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.preset.list --json`,
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.create-from-preset --preset-id token-consumption-trend --title "<title>" --open --json`,
  "```",
  "",
  "## Snapshots",
  "",
  "Create an immutable render snapshot from a `.csc` source path when you need a read-only shareable canvas view:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.snapshot.create --source-path .coder-studio/canvases/<title-slug>.csc --json`,
  "```",
  "",
  "Open the read-only snapshot route with:",
  "",
  "```text",
  "/embedded/canvas-snapshot/<snapshot-id>",
  "```",
  "",
  "## Clone",
  "",
  "Clone either an editable source canvas or a snapshot into a new editable `.csc` file:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.clone --source-path .coder-studio/canvases/<title-slug>.csc --title "<new-title>" --open --json`,
  "```",
  "",
  "## Render",
  "",
  "Prefer rendering from the `.csc` source path:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.render --source-path .coder-studio/canvases/<title-slug>.csc --json`,
  "```",
  "",
  "If you only have the canvas id, this also works:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.render --canvas <canvas-id> --json`,
  "```",
  "",
  "## Inspect",
  "",
  "Use semantic inspection when the agent needs compiled canvas data plus saved semantic comments for a selected rendered element:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" canvas.inspect --source-path .coder-studio/canvases/<title-slug>.csc --json`,
  "```",
  "",
  "If the user says the canvas changed, they added comments, or they annotated the canvas, re-run `canvas.inspect` on the same `.csc` source path.",
  "",
  "Use `canvas.render` for normal rendering and `canvas.inspect` when the task depends on selection/comment context from the canvas surface.",
  "",
  "## Notes",
  "",
  "- always use `--open` when creating a canvas so the user sees it immediately",
  "- new canvas source files are stored as readable `.coder-studio/canvases/<title-slug>.csc` paths in the workspace",
  "- title should be meaningful because it becomes the readable `.csc` slug",
  "- raw HTML like `<div>` or `<span>` is invalid in canvas source",
  "- keep diagrams small and focused; prefer multiple canvases over one overloaded diagram",
  "- always include `--json` for machine-readable output",
  "",
].join("\n");

export const CODER_STUDIO_CANVAS_SKILL: BuiltinSkillDefinition = {
  slug: "coder-studio-canvas",
  displayName: "Coder Studio Canvas",
  description: DESCRIPTION,
  version: "1.0.0",
  defaultEnabled: true,
  autoMountInMvp: true,
  files: [
    {
      relativePath: AUTOMATION_CMD_FILE_NAME,
      content: BUILTIN_AUTOMATION_BRIDGE_SOURCE,
    },
  ],
  mountRendering: "automation_bridge",
  content: CONTENT,
};
