import type { BuiltinSkillDefinition } from "./types.js";

const CONTENT = [
  "---",
  "name: coder-studio-memory",
  "description: Read and write durable Coder Studio workspace memory on demand.",
  "---",
  "",
  "# Coder Studio Memory",
  "",
  "Use this skill when you need to better understand the project or workspace context, look up durable debugging information, check important project rules, or leave stable follow-up context for future sessions.",
  "",
  "## Read On Demand",
  "",
  "Do not assume memory is injected at startup. Read workspace memory when you need to understand the project or context better, recover debugging information, verify commands or conventions, or review durable notes before making changes.",
  "",
  "Prefer targeted reads before broad reads:",
  "",
  "```bash",
  "coder-studio memory search architecture --workspace <workspace-id> --json",
  "coder-studio memory list --workspace <workspace-id> --type project --json",
  "coder-studio memory get <memory-id> --workspace <workspace-id> --json",
  "```",
  "",
  "If `CODER_STUDIO_WORKSPACE_ID` is set, you can omit `--workspace`:",
  "",
  "```bash",
  "coder-studio memory search testing --json",
  "```",
  "",
  "## Write Stable Context",
  "",
  "Write memory when you learn something durable that should help a future session, such as a confirmed project rule, a stable debugging conclusion, a reusable command, a repository convention, a technical constraint, a real follow-up todo, or an important feature constraint.",
  "",
  "Avoid transient scratch notes, temporary debugging observations, secrets, credentials, or anything the user would not expect to persist.",
  "",
  "Use `feature` for product behavior, `todo` for pending work, `bugfix` for defects, `project` for repository-operating knowledge, and `note` only as a fallback.",
  "",
  "Choose the narrowest type that matches the memory:",
  "",
  "- `feature`: stable facts about what the product does or should do.",
  "- `todo`: durable follow-up work that should remain visible later.",
  "- `bugfix`: confirmed defects, causes, or fixes that matter beyond the current turn.",
  "- `project`: repository-operating knowledge such as commands, conventions, directory expectations, or technical constraints.",
  "- `note`: only when the memory is durable but does not fit the other four types cleanly.",
  "",
  "Write direct, searchable content that will still make sense in a later session.",
  "",
  "```bash",
  'coder-studio memory add --workspace <workspace-id> --type project --content "This workspace uses pnpm for package scripts." --skill coder-studio-memory --json',
  "```",
  "",
  "Update or delete memory when it becomes stale:",
  "",
  "```bash",
  'coder-studio memory update <memory-id> --workspace <workspace-id> --content "Updated durable project context." --json',
  "coder-studio memory delete <memory-id> --workspace <workspace-id> --json",
  "```",
  "",
  "Users can inspect, edit, and delete workspace memory from the Memory side panel.",
  "",
].join("\n");

export const CODER_STUDIO_MEMORY_SKILL: BuiltinSkillDefinition = {
  slug: "coder-studio-memory",
  displayName: "Coder Studio Memory",
  description: "Read and write durable Coder Studio workspace memory on demand.",
  version: "1.0.0",
  defaultEnabled: true,
  autoMountInMvp: true,
  content: CONTENT,
};
