import {
  AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN,
  AUTOMATION_CMD_FILE_NAME,
  BUILTIN_AUTOMATION_BRIDGE_SOURCE,
} from "../automation-bridge.js";
import type { BuiltinSkillDefinition } from "./types.js";

const DESCRIPTION = "Read and write durable Coder Studio workspace memory on demand.";

const CONTENT = [
  "---",
  "name: coder-studio-memory",
  `description: ${DESCRIPTION}`,
  "---",
  "",
  "# Coder Studio Memory",
  "",
  "Use this skill when you need to better understand the project or workspace context, look up durable debugging information, check important project rules, or leave stable follow-up context for future sessions.",
  "",
  "## Read On Demand",
  "",
  "Do not assume memory is injected at startup. Read workspace memory when you need to understand the project or context better, recover debugging information, verify commands or conventions, or review durable notes before making changes.",
  "",
  "Prefer targeted reads before broad reads:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.search architecture --json`,
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.list --type wiki --json`,
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.get <memory-id> --json`,
  "```",
  "",
  "## Write Stable Context",
  "",
  "Write memory when you learn something durable that should help a future session, such as a confirmed project rule, a stable debugging conclusion, a reusable command, a repository convention, a technical constraint, a real follow-up todo, or an important feature constraint.",
  "",
  "Avoid transient scratch notes, temporary debugging observations, secrets, credentials, or anything the user would not expect to persist.",
  "",
  "Use `wiki` for durable project knowledge, `issue` for defects or verification items, `todo` for concrete follow-up work, and `note` only as a fallback.",
  "",
  "Choose the narrowest type that matches the memory:",
  "",
  "- `wiki`: repository-operating knowledge such as commands, conventions, architecture, directory expectations, or technical constraints.",
  "- `issue`: confirmed defects, investigation findings, or verification items that should remain visible later.",
  "- `todo`: durable follow-up work with a concrete next action.",
  "- `note`: durable context that does not fit the other three types cleanly.",
  "",
  "Status applies only to `issue` and `todo` memories. Use `not_started`, `in_progress`, `pending_verification`, or `completed` when the memory tracks work state.",
  "",
  "Write direct, searchable content that will still make sense in a later session.",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.create --type wiki --content "This workspace uses pnpm for package scripts." --skill coder-studio-memory --json`,
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.create --type issue --content "Verify release notes before publishing." --status pending_verification --skill coder-studio-memory --json`,
  "```",
  "",
  "Update or delete memory when it becomes stale:",
  "",
  "```bash",
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.update <memory-id> --content "Updated durable project context." --json`,
  `node "${AUTOMATION_CMD_ABSOLUTE_PATH_TOKEN}" memory.delete <memory-id> --json`,
  "```",
  "",
  "Users can inspect, edit, and delete workspace memory from the Memory side panel.",
  "",
].join("\n");

export const CODER_STUDIO_MEMORY_SKILL: BuiltinSkillDefinition = {
  slug: "coder-studio-memory",
  displayName: "Coder Studio Memory",
  description: DESCRIPTION,
  version: "1.0.0",
  defaultEnabled: true,
  autoMountInMvp: true,
  files: [
    {
      relativePath: AUTOMATION_CMD_FILE_NAME,
      content: BUILTIN_AUTOMATION_BRIDGE_SOURCE,
    },
  ],
  mountRendering: "automation_bridge",
  content: CONTENT,
};
